name: Canary release

on: workflow_dispatch

permissions:
  contents: read

jobs:
  canary-publish:
    name: Publish Packages (canary)
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn version --new-version "0.0.0-${GITHUB_SHA::8}" --no-git-tag-version
      - run: npm publish --access public --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
