name: Sync Repository

on:
  push:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

jobs:
  sync:
    permissions:
      contents: write  # for Git to git push
    if: github.repository == 'defi-wonderland/keep3r-network-v2-private'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Check out github repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: Install SSH Client
        uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 # v0.7.0
        with:
          ssh-private-key: ${{ secrets.SYNC_SSH_PRIVATE_KEY }}

      - name: Add Remote
        run: git remote add public git@github.com:defi-wonderland/keep3r-network-v2.git

      - name: Sync branch
        run: git push public ${{ github.ref_name }}
